### ISSUE TITLE
stretnutie s dr vojtekom, pre objasnenie niektorych problematik

### ISSUE THREAD

**Issue by bwooah** [TIS2022-FMFI/spektroskop-mikroskop#12]

**Comment by annoyingpart** [comment]
vystup zisteni
https://docs.google.com/document/d/16lfuPJwEOBhFPWBJcRgLLVD1WIlDKvuwJCSmRGW9G_U/edit#

**Comment by pavelpetrovic** [comment]
kod ku kalibraci
https://github.com/TIS2017/Spektrometer/blob/master/Spektrometer-TIS/Spektrometer/Logic/Calculators/GraphCalculator.cs

**Comment by bwooah** [comment]
to sme sa dohodli
