### ISSUE TITLE
Výsledný katalóg požiadaviek

### ISSUE THREAD

**Issue by bwooah** [TIS2022-FMFI/spektroskop-mikroskop#14]

**Comment by annoyingpart** [comment]
New version of KP 
https://docs.google.com/document/d/1U4mfwaaNh7e-NOazSO35RW_ckmLGTNMI/edit?usp=sharing&ouid=106442474851613723418&rtpof=true&sd=true

**Comment by bwooah** [comment]
cakame na review hlavne 3. casti potom uz hadam posledna iteracia uprav

**Comment by pavelpetrovic** [comment]
Pozrel som si KP. Mam pocit, ze tie veci, co sme minule zvyraznili este v tej druhej casti tam stale ostali zvyraznene. Zvyraznil som nejake dalsie v tretej casti, kde mam pocit, ze je to nejasne, alebo nedovysvetlene. Celkovo mam taky pocit, ze je v tom este trosilinecku chaos. Napr. podla mna by bolo normalne, aby aplikacia pri tom merani vzdy poukladala do pamate vsetko, co sa da namerat - co je viac ako nejake PNG, ktore je iba 2D - pre kazdy bod len jedna hodnota, lenze meranie je 3D - pre kazdy 2D bod meranej vzorky mame vektor intenzit pre vsetkych 1280 "vlnovych dlzok". Preto by podla mna aplikacia mala fungovat tak, ze ked sa nieco ulozi do suboru, tak sa predovsetkym ulozia vsetky tieto data. Z nich potom ked taketo meranie mame bud prave spravene, alebo nacitane zo suboru, je potom mozne v aplikacii zobrazovat tie tri rozne druhy grafov. Ale nie tak, ako to mate napisane, ze sa do aplikacie nacita nejake PNG, to je podla mna blbost. Aplikacia by mala vediet aj exportovat PNG, ale len pre prezentacne ucely, nepotrebuje ich znovu nacitavat, ale nacitavat data z merani a tie zobrazovat v lubovolnej verzii grafu, resp. porovnavat dve rozne merania.
