### ISSUE TITLE
návrh používateľského rozhrania

### ISSUE THREAD

**Issue by bwooah** [TIS2022-FMFI/spektroskop-mikroskop#19]

**Comment by bwooah** [comment]
prve stretnutie s dr vojtekom a prediskutovanie napadov, tie boli implementovane, bude sa treba s dr vojtekom znovu stretnut a odprezentovat mu zmeny, ten ale pribezny update dostal a moze s ho studovat sam zatial, pripadne dodat zmeny

**Comment by bwooah** [comment]
https://www.figma.com/file/hQ8SkSfh5cXZNDFcqbVntI/Untitled?node-id=0%3A1&t=qC9dLqAO6cigxOGa-1

**Comment by pavelpetrovic** [comment]
kopirujem l inku z duplicitneho issue #47

https://docs.google.com/document/d/1MaJpshMDfJMkYfeWn0-E_dg_9K-Gm8Oh0lwoEgMTZqM/edit#heading=h.j8tv7d6oeofh

**Comment by pavelpetrovic** [comment]
- na ciarovom grafe by sme asi radi videli aka hodnota v mm je vybrata slajderom dolu
- okrem toho viacerym veciam este nerozumieme a chceme ich dokladne prejst s Dr.Vojtekom na dlhom stretnuti, dovtedy si prosim zavolajte a ujasnite si tuto predstavu (a skonfrontujeme ju aj s dokumentom prilozenym)
