### ISSUE TITLE
Prva verzia katalogu poziadaviek

### ISSUE THREAD

**Issue by bwooah** [TIS2022-FMFI/spektroskop-mikroskop#2]
Ready when all bellow requirements are done:

TODO - #6 
TODO - #7 
TODO - #8 
TODO - #9

**Comment by annoyingpart** [comment]
TODO - #6 
TODO - #7 
TODO - #8 
TODO - 

- [ ]

**Comment by pavelpetrovic** [comment]
* Specifikácia popisuje ovládanie spektrometra, skúmanie spracovaného obrazu a spracovanie dát => to nie je presne, specifikacia popisuje poziadavky na tento softver, prosim upravit
* Katalóg požiadaviek slúži pre užívateľov, ktorí prídu do kontaktu so spektrometrom. => nielen, sluzi vsetkym zainteresovanym, t.j. zadavatelovi, vyvojarom i ostatnym
* v 1.1. chyba, ze KP je zavaznou dohodou pre zadavatela a vyvojarov o funkcionalite, ktoru bude aplikacia poskytovat
* zdrzte sa formulacii ako "Momentálne navrhovaná verzia"
* ", sledovať RGB zložku a sledovať jej intenzitu," - tomu nikto nerozumie, co sa touto formulaciou mysli
*  ale aj spätne načítať obraz a čítať z neho. => nie je z toho jasne, ze zo suboru a neviem co znamena citat z nacitaneho
* v slovniku pojmov zvyraznit slova
* "intenzita - miera rozloženia energie žiarenia do jednotlivých častí spektra" toto neviem skompilovat
* ostatne upravy priamo v google dokumente

**Comment by pavelpetrovic** [comment]
pridavam dokument zo stretnutia
[kp.odt](https://github.com/TIS2022-FMFI/spektroskop-mikroskop/files/9809712/kp.odt)
