### ISSUE TITLE
rozdelenie do tried, nahrubo na dohodu

### ISSUE THREAD

**Issue by bwooah** [TIS2022-FMFI/spektroskop-mikroskop#37]

**Comment by Benko11** [comment]
Class hierarchy is in place

**Comment by annoyingpart** [comment]
nemyslims si ze hierarchia tried je uz pevne dana...

**Comment by bwooah** [comment]
este sa mozu stat mensie zmeny v dependencies
nove classy su uz menej pravdepodobne
nakonci sa vygeneruje finalny class diagram cez pycharm plugin
