### ISSUE TITLE
Zobrazovanie druhej kamery

### ISSUE THREAD

**Issue by annoyingpart** [TIS2022-FMFI/spektroskop-mikroskop#56]
zistit akym sposobom sa ma zobrazovat vystup z 2. kamery

**Comment by bwooah** [comment]
niekedy to slo pomalsie, ale ked mi to julo ukazoval uz to slo rychlejsie, nicmenej odvtedy doslo k viacerym zefektivneniam a teda je to uz fajn
-co treba dorobit je button ktory okno znovu otvori miesto vzdy noveho setnutia kamery ak sa okno zavrie
